SHELL:=/bin/bash
TA=$(shell module load pgi64; pgaccelinfo|tail -1|awk '{if ($$1 == "PGI Compiler Option:") print $$4; else print "-ta=tesla:cc60"}')

all:
	module load pgi64; \
	pgcc -o lake_opti lake_opti.c -I./ -acc $(TA),time -fast -Minfo=accel -Minline -Msafeptr -Mnodepchk -lm

clean:
	rm -f *.o *~ *.dat *.png lake.log lake

